descriptor-schema-version: "2.5"

info:
  name: ubuntu-with-sshd-x86
  description: "Ubuntu Linux with SSHd. Login: root/root"
  version: "1.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

app:
  cpuarch: "x86_64"
  type: docker
  resources:
    profile: c1.large
    network:
      -
        interface-name: eth0
        ports:
            tcp:
              - 22

# Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["/usr/sbin/sshd", "-D"]
